### ISSUE TITLE
Debug message repeated a lot:  "[BWQ] Unhandled currency: ID 2245"

### ISSUE THREAD

**Issue by emersonrp** [Amadeus-/Broker_WorldQuests#10]
This message has started appearing rather prolifically, when looking at the addon tooltip, during zone changes, and in response to some other events I haven't pinned down yet.  It's happening a -lot-.

![image](https://github.com/Amadeus-/Broker_WorldQuests/assets/307232/27e76e28-0459-468e-8724-012968d7dd85)

This is on at least two different toons;  I haven't checked others but I assume it's the same there.

Thanks!

**Comment by Amadeus-** [comment]
@yoshimo Thanks for the pull request with the fix!
