### ISSUE TITLE
10.2.5 currency error

### ISSUE THREAD

**Issue by korgen63** [Amadeus-/Broker_WorldQuests#11]
The new 10.2.5 currency (Mysterious Fragment) gives the following error :
[BWQ] Unhandled currency: ID 2657

**Comment by Amadeus-** [comment]
I added code for this today.   I don't have a WQ-unlocked character to test with just yet -- so, I can't promise that it's implemented perfectly yet; however, the error messages should go away, at the least.

I'll test and make more updates once I get max level and unlock world quests.
