### ISSUE TITLE
Bug/Feature Request: Using Character specific settings moves defalut to old expansions

### ISSUE THREAD

**Issue by Feedy88** [Amadeus-/Broker_WorldQuests#13]
Hi,

I set "use character specific settings" to have different quests displayed, depending on Gear State, Rep-Level etc.

While it generally works, for some of my characters the Expansion selection defaults to old expansions instead of DF. I I tried to find a pattern but couldn't really. For some it falls back to BfA which is not even unlocked, for another char it swichted to SL. On a different char where BfA is also not unlocked, it properly defaults to DF.

As this could be a hard to find catch, my suggestion would be to add a "default expansion" setting as option to set. I am not firm with coding but saw the variable already exists, so let me know if that could be an option.

**Comment by Amadeus-** [comment]
I changed things a few versions ago to set the default expansion based upon criteria rather than having a hard-coded default.  I'm hoping/thinking this might have fixed your issue.

But, if you're still seeing a problem, please create a new issue and I'll look into it.
