### ISSUE TITLE
Please update 11.0

### ISSUE THREAD

**Issue by korgen63** [Amadeus-/Broker_WorldQuests#15]
It doesn't work with 11.0, need an update plz ^^

**Comment by Treacherouz** [comment]
I'm not an addon developer but through some tinkering and help from other addons I was able to troubleshoot the issue and get this working again without any lua errors. This is likely just a band-aid until Amadeus or xmyno are able to update.

**Replace lines 33 and 34 in "WorldQuests.lua" with**

local GetFactionInfoByID, GetQuestObjectiveInfo, GetNumQuestLogRewards, GetQuestLogRewardInfo, GetQuestLogRewardMoney, HaveQuestData
	= GetFactionInfoByID, GetQuestObjectiveInfo, GetNumQuestLogRewards, GetQuestLogRewardInfo, GetQuestLogRewardMoney, GetNumQuestLogRewardCurrencies, GetQuestLogRewardCurrencyInfo, HaveQuestData
	= C_Reputation.GetFactionDataByID, GetQuestObjectiveInfo, GetNumQuestLogRewards, GetQuestLogRewardInfo, GetQuestLogRewardMoney, HaveQuestData

local GetNumQuestLogRewardCurrencies, GetQuestLogRewardCurrencyInfo = GetNumQuestLogRewardCurrencies, GetQuestLogRewardCurrencyInfo
if not GetNumQuestLogRewardCurrencies then
	local reward_cache = {}
	local function GetData(questID)
		local data = reward_cache[questID]
		local t = GetTime()
		if not data or t > data.expTime then
			data = C_QuestLog.GetQuestRewardCurrencies(questID)
			data.expTime = t + 5
		end
		return data
	end
	function GetNumQuestLogRewardCurrencies(questID)
		local data = GetData(questID)
		return #data
	end
	function GetQuestLogRewardCurrencyInfo(i, questID)
		local data = GetData(questID)[i]
		if not data then
			return
		end
		return data.name, data.texture, data.baseRewardAmount, data.currencyID
		--data.totalRewardAmount
	end
end


**Also in "WorldQuests.lua", replace line 1913 with,**

button.factionFS:SetText(button.quest.factionID)


Hope this helps!

**Comment by Fofeee** [comment]
pasting exactly what you posted here i am getting the following error

`6x Broker_WorldQuests/WorldQuests.lua:1 Broker_WorldQuests/WorldQuests.lua:35: unexpected symbol near '='`

**Comment by Treacherouz** [comment]
I'm unable to reproduce the error but [here](https://mega.nz/file/FKpihZRK#9a2hApaw2u3TEuS-IfSEZPVa0BXv3IxFXeSLSOaq8Yo) is my full **Broker_WorldQuests** folder.

**Comment by korgen63** [comment]
The lua edition didn't work, broker worldquest disapeared from Titan Panel. But using your whole folder fixed it, thank you ^^

**Comment by Fofeee** [comment]
I dont know what was wrong with the pasted code and i didnt compare them, but the provided folder worked perfectly. Thank you very much!

**Comment by Amadeus-** [comment]
I've implemented the solution provided above.   I just returned to the game today and have been updated other addons, so I would have done it, but you all beat me to it! :)    Thanks!
