### ISSUE TITLE
TWW worldquests planned ?

### ISSUE THREAD

**Issue by korgen63** [Amadeus-/Broker_WorldQuests#17]
Is TWW content planned for Broker_WorldQuests ?

**Comment by yoshimo** [comment]
[Added zone IDs for first four TWW zones](https://github.com/Amadeus-/Broker_WorldQuests/commit/f1460b535c7abf3782c43ef705a73d53fc63425b) is already there, but testing is limited for a few more days ;)

**Comment by korgen63** [comment]
Thank you. I reached lev 80 but it still tells me "you need to unlock The War Within World Quests on one of your characters"
Do you know if there's another requirement to unlock it ?

**Comment by yoshimo** [comment]
```
if (expansion == CONSTANTS.EXPANSIONS.THEWARWITHIN) then
			hasUnlockedWorldQuests = UnitLevel("player") >= 78 and IsQuestFlaggedCompleted(84022) and IsQuestFlaggedCompleted(80592)	-- https://www.wowhead.com/beta/quest=84022/uniting-severed-threads and https://www.wowhead.com/quest=80592/forge-a-pact
```

guess we have a quest to do again :)

**Comment by korgen63** [comment]
Well guessed ! 1st quest is done but not the 2nd one. It's supposed to be a weekly meta quest and I'm pretty sure it's not available during the early access.

**Comment by Amadeus-** [comment]
I just unlocked world quests tonight myself, so I was able to update for basic support.   I will add zones and currencies as I unlock them.
