### ISSUE TITLE
Error 11.0.2.16

### ISSUE THREAD

**Issue by Agramon** [Amadeus-/Broker_WorldQuests#21]
I just installed 11.0.2.16 and I receive this error several times:

20x Broker_WorldQuests/Bounties.lua:73: attempt to call global 'FormatTimeLeftString' (a nil value)
[string "@Broker_WorldQuests/Bounties.lua"]:73: in function `UpdateBountyData'
[string "@Broker_WorldQuests/Factions.lua"]:168: in function `UpdateInfoPanel'
[string "@Broker_WorldQuests/WorldQuests.lua"]:1161: in function `UpdateBlock'
[string "@Broker_WorldQuests/WorldQuests.lua"]:1153: in function `RunUpdate'
[string "@Broker_WorldQuests/WorldQuests.lua"]:1621: in function <Broker_WorldQuests/WorldQuests.lua:1613>

**Comment by Amadeus-** [comment]
Fixed in version 11.0.2.17!
