### ISSUE TITLE
Broker_WorldQuests/WorldQuests.lua:272: Usage: HaveQuestData(questID

### ISSUE THREAD

**Issue by yoshimo** [Amadeus-/Broker_WorldQuests#22]
```
24x Broker_WorldQuests/24x Broker_WorldQuests/WorldQuests.lua:272: Usage: HaveQuestData(questID
[string "=[C]"]: in function `HaveQuestData'
[string "@Broker_WorldQuests/WorldQuests.lua"]:272: in function <Broker_WorldQuests/WorldQuests.lua:257>
[string "@Broker_WorldQuests/WorldQuests.lua"]:950: in function `UpdateQuestData'
[string "@Broker_WorldQuests/WorldQuests.lua"]:1135: in function `UpdateBlock'
[string "@Broker_WorldQuests/WorldQuests.lua"]:1120: in function `RunUpdate'
[string "@Broker_WorldQuests/WorldQuests.lua"]:1604: in function <Broker_WorldQuests/WorldQuests.lua:1596>

```

debug settings only give this:

`[BWQ] questList.1: ID: nil (mapId: 2024)`

**Comment by Amadeus-** [comment]
[WorldQuests.zip](https://github.com/user-attachments/files/17090687/WorldQuests.zip)

Replace your WorldQuests.lua file with this one (attached) and see if that resolves the issue.   It's involving a past expansion so I don't want to take the time to track down "why" it's happening in that particular zone, etc.   But, this adds a sanity check that should have it skip the routine that it's trying to do when the data isn't there.

**Comment by yoshimo** [comment]
https://github.com/smaitch/Grail/issues/365
looks like the upper case change affects various addons on the ptr

**Comment by Amadeus-** [comment]
Well, you didn't mention you were on the PTR....    In the future, please state this as I am expecting bug reports and other requests to be referencing the Live client.   I would obviously fix it myself once I saw it on the live client.

But, I'll go ahead and look into what's changed with the PTR and make that adjustment so that it's fixed.

**Comment by Amadeus-** [comment]
As stated above, I'm not supporting the PTR with this addon.   If this issue persists once the changes go Live, I'll fix it at that point.
