### ISSUE TITLE
BUG: Debug error spammed in chat [BWQ] Unhandled currency: ID 1742

### ISSUE THREAD

**Issue by Agramon** [Amadeus-/Broker_WorldQuests#5]
On my priest alt, I got spammed every few seconds by the following error message:
[BWQ] Unhandled currency: ID 1742

According to wowhead, this is a hidden currency from Mechagon (Rustbolt Resistance)
[https://www.wowhead.com/currency=1742](https://www.wowhead.com/currency=1742)

I suggest just ignoring this currency (and not spam my chat)

**Comment by Amadeus-** [comment]
@Agramon I can take care of this.  I likely won't put in support for this in the settings/filters (i.e., you won't be able to filter by it, etc.)   But, I can make the addon support it without the spam and include it as a valid world quest, etc.

Just to confirm, you're seeing this when you're viewing the **Battle For Azeroth** World Quests tab, correct?

**Comment by Amadeus-** [comment]
@Agramon I pushed out version 10.0.2.7 that should remove that spam and include that reputation currency with the other Battle For Azeroth reputation currencies.

Let me know if everything is working properly and I'll then close this issue.

**Comment by Agramon** [comment]
> @Agramon I can take care of this. I likely won't put in support for this in the settings/filters (i.e., you won't be able to filter by it, etc.) But, I can make the addon support it without the spam and include it as a valid world quest, etc.
> 
> Just to confirm, you're seeing this when you're viewing the **Battle For Azeroth** World Quests tab, correct?

I think it is maybe ethe "Security First" world quest on Mechagon.

**Comment by Agramon** [comment]
> @Agramon I pushed out version 10.0.2.7 that should remove that spam and include that reputation currency with the other Battle For Azeroth reputation currencies.
> 
> Let me know if everything is working properly and I'll then close this issue.

I installed it and I no longer have the error on my alt. Seems to be working, thanks.
