### ISSUE TITLE
(Suggestion) Add World Event Timers

### ISSUE THREAD

**Issue by shadofall** [Amadeus-/Broker_WorldQuests#6]
Hello,
I was thinking it might be nice to have Timers for World Event Timers for DragonFlight events Such as

Dragonbane keep
Community Feast
Grand Hunts

Pretty much any  event that will Persist through the course of the expansion

These timers appear on the world map when an event is in progress or preparing to start. but sometimes are hidden by quest/world quest icons.  would also mean not having to pull up wowhead to see the next start time

This maybe better served by a new addon rather than incorporating it in to this one, but so far i haven't found one. did find a  Weak Auras that does this but i'd like to have it in a broker bar   (the wa is a little over kill but figured its a good base example)

https://wago.io/TamasDragonflightHelper

**Comment by b-morgan** [comment]
I strongly agree that this would be an excellent addition.

**Comment by Amadeus-** [comment]
I didn't really play Dragonflight, but I'm now playing again with The War Within.   Are there events like this that are applicable to The War Within expansion?  If so, please list them, etc.

**Comment by b-morgan** [comment]
I haven't played TWW long enough but I would suggest that a good first start would be the events that Wowhead.com publishes on their main page, Today in WoW section.

**Comment by shadofall** [comment]
> I haven't played TWW long enough but I would suggest that a good first start would be the events that Wowhead.com publishes on their main page, Today in WoW section.

this would probably be the best advice to watch., but at current the only two timed events i know of are the hourly theater troupe in isle of dorn. that last for 10 min. and the Beldar's shadow shift in hallowfall which lasts for 30 min then starts again 3 later.

**Comment by Amadeus-** [comment]
Yea, that's why I asked.  Everything I'm seeing now is set to specific times so they're easy to keep track of.   This is more common for modern MMOs, so they may be moving away from folks having to worry about being notified when an event becomes available.

**Comment by b-morgan** [comment]
Even with specific times I'd like to keep track of things like the Dragon Isle's Community Feast.

**Comment by Amadeus-** [comment]
I doubt seriously that I will be going back to old content to add things, unless it turns out that I need it personally.  But, I did just now add support for the new locked "Special Assignment" world quests  ...and it wasn't a trivial thing.

If someone else wants to add support for past expansion features, I'll be happy to merge it with my version if they submit a pull request.
