### ISSUE TITLE
Per-character settings always defaults to showing BFA world quests on reload

### ISSUE THREAD

**Issue by speedwaystar** [Amadeus-/Broker_WorldQuests#7]
they should default to either showing Dragonflight world quests, or whatever expansion was last selected by the user.
note that the global settings (non per-character) correctly remmber the last used setting.

**Comment by Amadeus-** [comment]
I want to make sure I understand exactly what you're saying.   Are you saying that every time you go to a character, it resets back to BFA?   Or, are you saying that once you choose Dragonflight on one character, then the others should automatically switch ...but aren't?

Outline for me exactly what is currently happening so I can understand what you mean.  It's not exactly clear what you want to be happening and what is currently happening.

**Comment by speedwaystar** [comment]
it's very easy to reproduce. set broker_worldquests to use per character
profiles, then set it to show Shadowlands. reloadui. it's now showing BFA.

**Comment by Amadeus-** [comment]
> it's very easy to reproduce. set broker_worldquests to use per character profiles, then set it to show Shadowlands. reloadui. it's now showing BFA.

@speedwaystar OK -- let me find some time after the holidays and I'll see if I can figure out what's happening.

**Comment by matnledsmsadkdad** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!
