### ISSUE TITLE
Add TomTom Waypoint - not replace

### ISSUE THREAD

**Issue by PremierJosh** [Amadeus-/Broker_WorldQuests#8]
Currently, left clicking just replaces the current TomTom waypoint. It would be nice if it just added a new one - so I can go through the list, left click the ones I want, and then just go from waypoint to waypoint.

**Comment by Amadeus-** [comment]
This is a good idea.  Once I get world quests unlocked for Dragonflight, I'll look into making this adjustment.   Or, at least, adding it as an option.

**Comment by Amadeus-** [comment]
This feature will be added in the next released version, 11.0.2.15
